POST http://localhost:3003/api/diaries
Content-Type: application/json

{
    "date": "2023-08-05",
    "weather": "sunny",
    "visibility":"good",
    "comment":"good stuff but scary"
}

###
GET http://localhost:3003/api/diaries